import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export const LANGUAGES = [
  { code: "en", label: "English", native: "English" },
  { code: "de", label: "German", native: "Deutsch" },
  { code: "nl", label: "Dutch", native: "Nederlands" },
  { code: "fr", label: "French", native: "Français" },
  { code: "es", label: "Spanish", native: "Español" },
  { code: "pt", label: "Portuguese", native: "Português" },
  { code: "ar", label: "Arabic", native: "العربية" },
  { code: "zh", label: "Mandarin", native: "中文" },
] as const;

export type LangCode = (typeof LANGUAGES)[number]["code"];

const en = {
  // Sections / navigation
  feed: "Global Feed",
  notebooks: "My Private Notebooks",
  suggestions: "Suggestions Box",
  drawing: "Drawing Studio",
  sandbox: "Tactical Sandbox",
  wiki: "World Wiki / Codex",
  settings: "Settings",
  jumpToSection: "Jump to a section",
  openMenu: "Open menu",
  madeBy: "Made by",

  // Settings
  account: "Account",
  signOut: "Sign out",
  signIn: "Sign in",
  signedInAs: "Signed in as",
  guest: "Browsing as guest",
  language: "Language",
  languageHint: "Choose the language for the app interface.",
  appearance: "Appearance",
  darkOnly: "Writer Creators uses a dark studio theme.",

  // World Wiki
  wikiSubtitle: "Your codex of characters, factions, locations and gear.",
  allCategories: "All",
  catCharacters: "Characters",
  catFactions: "Factions",
  catLocations: "Locations",
  catGear: "Military Gear",
  addEntry: "New entry",
  entryTitlePh: "Name",
  entrySummaryPh: "One-line summary",
  entryDetailsPh: "Full details, history, notes…",
  deleteEntry: "Delete entry",
  noWikiEntries: "No entries yet. Add your first codex entry.",
  searchWiki: "Search the codex…",
  signInRequired: "Sign in to use this feature.",
  entrySaved: "Saved",
  category: "Category",

  // Auto-hyperlinking
  highlightLore: "Lore links",
  editMode: "Edit text",
  loreLinkHint: "Tap a highlighted name to see its codex card.",
  noMatches: "No codex terms found in this text yet.",
  openInWiki: "Open in codex",
  close: "Close",

  // Notebook tabs / actions
  write: "Write",
  characters: "Characters",
  timeline: "Timeline",
  lore: "Lore",
  startWriting: "Start writing your story…",
  copyText: "Copy text",
  copied: "Story copied to clipboard",
  copyFailed: "Couldn't copy — try again",
  fixGrammar: "Fix grammar",

  // Tutorial
  tutAria: "Getting started tour",
  tutSkip: "Skip tour",
  tutBack: "Back",
  tutNext: "Next",
  tutStart: "Start creating",
  tutWelcomeTitle: "Welcome to Writer Creator",
  tutWelcomeBody: "A single workspace for drafting fiction, designing your cast, mapping your world and sharing chapters with readers. Here's a 30-second tour.",
  tutWriterTitle: "Writer Tools",
  tutWriterBody: "Open Notebooks to write chapters with auto-save, track characters and lore, plan your timeline, set word goals and invite collaborators to a shared notebook chat.",
  tutWikiTitle: "World Wiki & Lore Links",
  tutWikiBody: "Build a codex of characters, factions, locations and gear. While writing, saved names are highlighted automatically — tap one to open its lore card without leaving the editor.",
  tutCanvasTitle: "Drawing Canvas",
  tutCanvasBody: "The Art Studio gives you brushes, a paint bucket, layers, a stroke stabilizer and custom canvas sizes — perfect for character sketches and comic pages.",
  tutMapTitle: "Tactical Map",
  tutMapBody: "In the Tactical Sandbox you can upload a map, sketch terrain, draw vector route arrows, drop glowing markers, add text labels and organise it all with layers.",
  nbTitle: "Notebooks",
  nbSubtitle: "Private scratchpad with AI grammar fix.",
  nbNone: "No notebooks yet",
  nbNoneHint: "Tap “New” to start one.",
  newLabel: "New",
  phTitle: "Title",
  deleteNotebook: "Delete notebook",
  tNothingToFix: "Nothing to fix yet — write something first.",
  tGrammarFail: "Couldn't reach the grammar assistant.",
  tSignInPost: "Sign in to post.",
  tSignInSubmit: "Please sign in to submit.",
  tAddTitle: "Add a title first.",
  tUserNotFound: "User not found.",
  tSubmitted: "Submitted — staff will review.",
  sgBugs: "Bug Reports",
  sgFeatures: "Feature Suggestions",
  sgMedia: "Video / Media Bug Reports",
  sgUser: "Report a User",
  phSteps: "Steps to reproduce…",
  phIdeaTitle: "Idea title",
  phFeature: "Describe the feature…",
  phWhatBroke: "What broke?",
  phContext: "Context (timestamp, device, etc.)",
  phUsername: "Username (e.g. alice)",
  phWhatHappened: "What happened? Be specific.",
  tInvalidDims: "Enter valid dimensions.",
  tLayerLimit: "Layer limit reached (8).",
  tNeedLayer: "Need at least one layer.",
  toggleSide: "Toggle side panel",
  layers: "Layers",
  addLayer: "Add layer",
  deleteLayer: "Delete layer",
  actions: "Actions",
  color: "Color",
  colorWheel: "Color wheel",
  clearCanvas: "Clear canvas",
  undo: "Undo",
  redo: "Redo",
  undoAria: "Undo last action",
  redoAria: "Redo last undone action",
  sizeLabel: "Size",
  opacityLabel: "Opacity",
  stabilizer: "Stabilizer",
  stabilizerAria: "Stroke stabilizer strength",
  canvasSizeLabel: "Canvas size",
  customLabel: "Custom",
  customWidth: "Custom canvas width",
  customHeight: "Custom canvas height",
  tImageFail: "Couldn't read that image.",
  tMaxPages: "Max 30 pages per comic post.",
  tImageLoadFail: "One of those images failed to load.",
  tAddComicPage: "Add at least one comic page.",
  tWriteSomething: "Write something or add a title.",
  tWordLimit: "500-word limit reached.",
  tPosted: "Posted.",
  tSignInReport: "Sign in to report.",
  tReported: "Reported — sent to the mod queue.",
  tSignInLike: "Sign in to like.",
  tSignInComment: "Sign in to comment.",
  searchPh: "Search #tags or @users",
  shareStory: "Share a story",
  autoSavedDraft: "Auto-saved as draft",
  removeImage: "Remove image",
  removeCover: "Remove cover",
  linkProject: "Link to a project…",
  removePage: "Remove page",
  swipeHint: "Swipe up to explore stories",
  commentsLabel: "Comments",
  beFirstComment: "Be the first to comment.",
  addCommentPh: "Add a comment…",
  novelTag: "Novel",
  comicTag: "Comic",
  likeLabel: "Like",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",

  // Character wiki additions
  addCharacter: "Add character",
  noCharacters: "No characters yet.",
  filterByRole: "Filter by tag",
  filterAll: "All",
  blankCardWarning: "Finish the blank card before adding another.",
  charNamePh: "Character name",
} as const;

export type Key = keyof typeof en;

const DICT: Record<LangCode, Partial<Record<Key, string>>> = {
  en: {},
  de: {
    feed: "Globaler Feed",
    notebooks: "Meine privaten Notizbücher",
    suggestions: "Vorschlagsbox",
    drawing: "Zeichenstudio",
    sandbox: "Taktischer Sandkasten",
    wiki: "Welt-Wiki / Kodex",
    settings: "Einstellungen",
    jumpToSection: "Zu einem Bereich springen",
    openMenu: "Menü öffnen",
    madeBy: "Erstellt von",
    account: "Konto",
    signOut: "Abmelden",
    signIn: "Anmelden",
    signedInAs: "Angemeldet als",
    guest: "Als Gast unterwegs",
    language: "Sprache",
    languageHint: "Wähle die Sprache der Benutzeroberfläche.",
    appearance: "Darstellung",
    darkOnly: "Writer Creators nutzt ein dunkles Studio-Design.",
    wikiSubtitle: "Dein Kodex für Figuren, Fraktionen, Orte und Ausrüstung.",
    allCategories: "Alle",
    catCharacters: "Figuren",
    catFactions: "Fraktionen",
    catLocations: "Orte",
    catGear: "Militärische Ausrüstung",
    addEntry: "Neuer Eintrag",
    entryTitlePh: "Name",
    entrySummaryPh: "Kurzbeschreibung in einer Zeile",
    entryDetailsPh: "Details, Geschichte, Notizen…",
    deleteEntry: "Eintrag löschen",
    noWikiEntries: "Noch keine Einträge. Füge deinen ersten Kodex-Eintrag hinzu.",
    searchWiki: "Kodex durchsuchen…",
    signInRequired: "Melde dich an, um diese Funktion zu nutzen.",
    entrySaved: "Gespeichert",
    category: "Kategorie",
    highlightLore: "Lore-Links",
    editMode: "Text bearbeiten",
    loreLinkHint: "Tippe auf einen markierten Namen, um die Kodex-Karte zu sehen.",
    noMatches: "In diesem Text wurden noch keine Kodex-Begriffe gefunden.",
    openInWiki: "Im Kodex öffnen",
    close: "Schließen",
    write: "Schreiben",
    characters: "Figuren",
    timeline: "Zeitachse",
    lore: "Lore",
    startWriting: "Beginne deine Geschichte…",
    copyText: "Text kopieren",
    copied: "Geschichte in die Zwischenablage kopiert",
    copyFailed: "Kopieren fehlgeschlagen — versuche es erneut",
    fixGrammar: "Grammatik korrigieren",
    tutAria: "Einführungstour",
    tutSkip: "Tour überspringen",
    tutBack: "Zurück",
    tutNext: "Weiter",
    tutStart: "Los geht's",
    tutWelcomeTitle: "Willkommen bei Writer Creator",
    tutWelcomeBody: "Ein Arbeitsbereich zum Schreiben von Geschichten, Gestalten deiner Figuren, Kartieren deiner Welt und Teilen von Kapiteln. Hier eine 30-Sekunden-Tour.",
    tutWriterTitle: "Schreibwerkzeuge",
    tutWriterBody: "Öffne Notizbücher, um Kapitel mit Auto-Speichern zu schreiben, Figuren und Lore zu verwalten, deine Zeitachse zu planen, Wortziele zu setzen und Mitautoren in den Notizbuch-Chat einzuladen.",
    tutWikiTitle: "Welt-Wiki & Lore-Links",
    tutWikiBody: "Baue einen Kodex aus Figuren, Fraktionen, Orten und Ausrüstung. Beim Schreiben werden gespeicherte Namen automatisch markiert — tippe darauf, um die Lore-Karte zu öffnen, ohne den Editor zu verlassen.",
    tutCanvasTitle: "Zeichenfläche",
    tutCanvasBody: "Das Kunststudio bietet Pinsel, Farbeimer, Ebenen, einen Strich-Stabilisator und eigene Leinwandgrößen — perfekt für Figurenskizzen und Comicseiten.",
    tutMapTitle: "Taktische Karte",
    tutMapBody: "Im Taktischen Sandkasten kannst du Karten hochladen, Gelände skizzieren, Routenpfeile zeichnen, leuchtende Marker setzen, Textlabels hinzufügen und alles in Ebenen organisieren.",
    nbTitle: "Notizbücher",
    nbSubtitle: "Privater Notizblock mit KI-Grammatikkorrektur.",
    nbNone: "Noch keine Notizbücher",
    nbNoneHint: "Tippe auf „Neu“, um zu starten.",
    newLabel: "Neu",
    phTitle: "Titel",
    deleteNotebook: "Notizbuch löschen",
    tNothingToFix: "Noch nichts zu korrigieren – schreibe zuerst etwas.",
    tGrammarFail: "Grammatik-Assistent nicht erreichbar.",
    tSignInPost: "Melde dich an, um zu posten.",
    tSignInSubmit: "Bitte melde dich an, um zu senden.",
    tAddTitle: "Füge zuerst einen Titel hinzu.",
    tUserNotFound: "Benutzer nicht gefunden.",
    tSubmitted: "Gesendet – das Team prüft es.",
    sgBugs: "Fehlerberichte",
    sgFeatures: "Funktionsvorschläge",
    sgMedia: "Video-/Medien-Fehlerberichte",
    sgUser: "Nutzer melden",
    phSteps: "Schritte zur Reproduktion…",
    phIdeaTitle: "Titel der Idee",
    phFeature: "Beschreibe die Funktion…",
    phWhatBroke: "Was ist kaputt?",
    phContext: "Kontext (Zeitstempel, Gerät usw.)",
    phUsername: "Benutzername (z. B. alice)",
    phWhatHappened: "Was ist passiert? Sei konkret.",
    tInvalidDims: "Gib gültige Maße ein.",
    tLayerLimit: "Ebenenlimit erreicht (8).",
    tNeedLayer: "Mindestens eine Ebene nötig.",
    toggleSide: "Seitenleiste umschalten",
    layers: "Ebenen",
    addLayer: "Ebene hinzufügen",
    deleteLayer: "Ebene löschen",
    actions: "Aktionen",
    color: "Farbe",
    colorWheel: "Farbkreis",
    clearCanvas: "Leinwand leeren",
    undo: "Rückgängig",
    redo: "Wiederholen",
    undoAria: "Letzte Aktion rückgängig machen",
    redoAria: "Rückgängig gemachte Aktion wiederholen",
    sizeLabel: "Größe",
    opacityLabel: "Deckkraft",
    stabilizer: "Stabilisator",
    stabilizerAria: "Stärke des Strichstabilisators",
    canvasSizeLabel: "Leinwandgröße",
    customLabel: "Benutzerdefiniert",
    customWidth: "Benutzerdefinierte Breite",
    customHeight: "Benutzerdefinierte Höhe",
    tImageFail: "Bild konnte nicht gelesen werden.",
    tMaxPages: "Max. 30 Seiten pro Comic-Beitrag.",
    tImageLoadFail: "Ein Bild konnte nicht geladen werden.",
    tAddComicPage: "Füge mindestens eine Comicseite hinzu.",
    tWriteSomething: "Schreibe etwas oder füge einen Titel hinzu.",
    tWordLimit: "500-Wörter-Grenze erreicht.",
    tPosted: "Veröffentlicht.",
    tSignInReport: "Melde dich an, um zu melden.",
    tReported: "Gemeldet – an die Moderation gesendet.",
    tSignInLike: "Melde dich an, um zu liken.",
    tSignInComment: "Melde dich an, um zu kommentieren.",
    searchPh: "#Tags oder @Nutzer suchen",
    shareStory: "Geschichte teilen",
    autoSavedDraft: "Automatisch als Entwurf gespeichert",
    removeImage: "Bild entfernen",
    removeCover: "Cover entfernen",
    linkProject: "Mit Projekt verknüpfen…",
    removePage: "Seite entfernen",
    swipeHint: "Nach oben wischen für weitere Geschichten",
    commentsLabel: "Kommentare",
    beFirstComment: "Sei der Erste, der kommentiert.",
    addCommentPh: "Kommentar hinzufügen…",
    novelTag: "Roman",
    comicTag: "Comic",
    likeLabel: "Gefällt mir",
    zoomIn: "Vergrößern",
    zoomOut: "Verkleinern",
    addCharacter: "Charakter hinzuf\u00fcgen",
    noCharacters: "Noch keine Charaktere.",
    filterByRole: "Nach Tag filtern",
    filterAll: "Alle",
    blankCardWarning: "Vervollst\u00e4ndige die leere Karte, bevor du eine neue hinzuf\u00fcgst.",
    charNamePh: "Charaktername",
  },
    feed: "Globaler Feed",
    notebooks: "Meine privaten Notizbücher",
    suggestions: "Vorschlagsbox",
    drawing: "Zeichenstudio",
    sandbox: "Taktischer Sandkasten",
    wiki: "Welt-Wiki / Kodex",
    settings: "Einstellungen",
    jumpToSection: "Zu einem Bereich springen",
    openMenu: "Menü öffnen",
    madeBy: "Erstellt von",
    account: "Konto",
    signOut: "Abmelden",
    signIn: "Anmelden",
    signedInAs: "Angemeldet als",
    guest: "Als Gast unterwegs",
    language: "Sprache",
    languageHint: "Wähle die Sprache der Benutzeroberfläche.",
    appearance: "Darstellung",
    darkOnly: "Writer Creators nutzt ein dunkles Studio-Design.",
    wikiSubtitle: "Dein Kodex für Figuren, Fraktionen, Orte und Ausrüstung.",
    allCategories: "Alle",
    catCharacters: "Figuren",
    catFactions: "Fraktionen",
    catLocations: "Orte",
    catGear: "Militärische Ausrüstung",
    addEntry: "Neuer Eintrag",
    entryTitlePh: "Name",
    entrySummaryPh: "Kurzbeschreibung in einer Zeile",
    entryDetailsPh: "Details, Geschichte, Notizen…",
    deleteEntry: "Eintrag löschen",
    noWikiEntries: "Noch keine Einträge. Füge deinen ersten Kodex-Eintrag hinzu.",
    searchWiki: "Kodex durchsuchen…",
    signInRequired: "Melde dich an, um diese Funktion zu nutzen.",
    entrySaved: "Gespeichert",
    category: "Kategorie",
    highlightLore: "Lore-Links",
    editMode: "Text bearbeiten",
    loreLinkHint: "Tippe auf einen markierten Namen, um die Kodex-Karte zu sehen.",
    noMatches: "In diesem Text wurden noch keine Kodex-Begriffe gefunden.",
    openInWiki: "Im Kodex öffnen",
    close: "Schließen",
    write: "Schreiben",
    characters: "Figuren",
    timeline: "Zeitachse",
    lore: "Lore",
    startWriting: "Beginne deine Geschichte…",
    copyText: "Text kopieren",
    copied: "Geschichte in die Zwischenablage kopiert",
    copyFailed: "Kopieren fehlgeschlagen — versuche es erneut",
    fixGrammar: "Grammatik korrigieren",
    tutAria: "Einführungstour",
    tutSkip: "Tour überspringen",
    tutBack: "Zurück",
    tutNext: "Weiter",
    tutStart: "Los geht's",
    tutWelcomeTitle: "Willkommen bei Writer Creator",
    tutWelcomeBody: "Ein Arbeitsbereich zum Schreiben von Geschichten, Gestalten deiner Figuren, Kartieren deiner Welt und Teilen von Kapiteln. Hier eine 30-Sekunden-Tour.",
    tutWriterTitle: "Schreibwerkzeuge",
    tutWriterBody: "Öffne Notizbücher, um Kapitel mit Auto-Speichern zu schreiben, Figuren und Lore zu verwalten, deine Zeitachse zu planen, Wortziele zu setzen und Mitautoren in den Notizbuch-Chat einzuladen.",
    tutWikiTitle: "Welt-Wiki & Lore-Links",
    tutWikiBody: "Baue einen Kodex aus Figuren, Fraktionen, Orten und Ausrüstung. Beim Schreiben werden gespeicherte Namen automatisch markiert — tippe darauf, um die Lore-Karte zu öffnen, ohne den Editor zu verlassen.",
    tutCanvasTitle: "Zeichenfläche",
    tutCanvasBody: "Das Kunststudio bietet Pinsel, Farbeimer, Ebenen, einen Strich-Stabilisator und eigene Leinwandgrößen — perfekt für Figurenskizzen und Comicseiten.",
    tutMapTitle: "Taktische Karte",
    tutMapBody: "Im Taktischen Sandkasten kannst du Karten hochladen, Gelände skizzieren, Routenpfeile zeichnen, leuchtende Marker setzen, Textlabels hinzufügen und alles in Ebenen organisieren.",
    nbTitle: "Notizbücher",
    nbSubtitle: "Privater Notizblock mit KI-Grammatikkorrektur.",
    nbNone: "Noch keine Notizbücher",
    nbNoneHint: "Tippe auf „Neu“, um zu starten.",
    newLabel: "Neu",
    phTitle: "Titel",
    deleteNotebook: "Notizbuch löschen",
    tNothingToFix: "Noch nichts zu korrigieren – schreibe zuerst etwas.",
    tGrammarFail: "Grammatik-Assistent nicht erreichbar.",
    tSignInPost: "Melde dich an, um zu posten.",
    tSignInSubmit: "Bitte melde dich an, um zu senden.",
    tAddTitle: "Füge zuerst einen Titel hinzu.",
    tUserNotFound: "Benutzer nicht gefunden.",
    tSubmitted: "Gesendet – das Team prüft es.",
    sgBugs: "Fehlerberichte",
    sgFeatures: "Funktionsvorschläge",
    sgMedia: "Video-/Medien-Fehlerberichte",
    sgUser: "Nutzer melden",
    phSteps: "Schritte zur Reproduktion…",
    phIdeaTitle: "Titel der Idee",
    phFeature: "Beschreibe die Funktion…",
    phWhatBroke: "Was ist kaputt?",
    phContext: "Kontext (Zeitstempel, Gerät usw.)",
    phUsername: "Benutzername (z. B. alice)",
    phWhatHappened: "Was ist passiert? Sei konkret.",
    tInvalidDims: "Gib gültige Maße ein.",
    tLayerLimit: "Ebenenlimit erreicht (8).",
    tNeedLayer: "Mindestens eine Ebene nötig.",
    toggleSide: "Seitenleiste umschalten",
    layers: "Ebenen",
    addLayer: "Ebene hinzufügen",
    deleteLayer: "Ebene löschen",
    actions: "Aktionen",
    color: "Farbe",
    colorWheel: "Farbkreis",
    clearCanvas: "Leinwand leeren",
    undo: "Rückgängig",
    redo: "Wiederholen",
    undoAria: "Letzte Aktion rückgängig machen",
    redoAria: "Rückgängig gemachte Aktion wiederholen",
    sizeLabel: "Größe",
    opacityLabel: "Deckkraft",
    stabilizer: "Stabilisator",
    stabilizerAria: "Stärke des Strichstabilisators",
    canvasSizeLabel: "Leinwandgröße",
    customLabel: "Benutzerdefiniert",
    customWidth: "Benutzerdefinierte Breite",
    customHeight: "Benutzerdefinierte Höhe",
    tImageFail: "Bild konnte nicht gelesen werden.",
    tMaxPages: "Max. 30 Seiten pro Comic-Beitrag.",
    tImageLoadFail: "Ein Bild konnte nicht geladen werden.",
    tAddComicPage: "Füge mindestens eine Comicseite hinzu.",
    tWriteSomething: "Schreibe etwas oder füge einen Titel hinzu.",
    tWordLimit: "500-Wörter-Grenze erreicht.",
    tPosted: "Veröffentlicht.",
    tSignInReport: "Melde dich an, um zu melden.",
    tReported: "Gemeldet – an die Moderation gesendet.",
    tSignInLike: "Melde dich an, um zu liken.",
    tSignInComment: "Melde dich an, um zu kommentieren.",
    searchPh: "#Tags oder @Nutzer suchen",
    shareStory: "Geschichte teilen",
    autoSavedDraft: "Automatisch als Entwurf gespeichert",
    removeImage: "Bild entfernen",
    removeCover: "Cover entfernen",
    linkProject: "Mit Projekt verknüpfen…",
    removePage: "Seite entfernen",
    swipeHint: "Nach oben wischen für weitere Geschichten",
    commentsLabel: "Kommentare",
    beFirstComment: "Sei der Erste, der kommentiert.",
    addCommentPh: "Kommentar hinzufügen…",
    novelTag: "Roman",
    comicTag: "Comic",
    likeLabel: "Gefällt mir",
    zoomIn: "Vergrößern",
    zoomOut: "Verkleinern",
    addCharacter: "Charakter hinzuf\u00fcgen",
    noCharacters: "Noch keine Charaktere.",
    filterByRole: "Nach Tag filtern",
    filterAll: "Alle",
    blankCardWarning: "Vervollst\u00e4ndige die leere Karte, bevor du eine neue hinzuf\u00fcgst.",
    charNamePh: "Charaktername",
  },
  nl: {
    feed: "Globale feed",
    notebooks: "Mijn privénotitieboeken",
    suggestions: "Suggestiebox",
    drawing: "Tekenstudio",
    sandbox: "Tactische zandbak",
    wiki: "Wereld-wiki / Codex",
    settings: "Instellingen",
    jumpToSection: "Ga naar een onderdeel",
    openMenu: "Menu openen",
    madeBy: "Gemaakt door",
    account: "Account",
    signOut: "Afmelden",
    signIn: "Aanmelden",
    signedInAs: "Aangemeld als",
    guest: "Je bekijkt als gast",
    language: "Taal",
    languageHint: "Kies de taal van de interface.",
    appearance: "Weergave",
    darkOnly: "Writer Creators gebruikt een donker studiothema.",
    wikiSubtitle: "Jouw codex van personages, facties, locaties en uitrusting.",
    allCategories: "Alles",
    catCharacters: "Personages",
    catFactions: "Facties",
    catLocations: "Locaties",
    catGear: "Militaire uitrusting",
    addEntry: "Nieuw item",
    entryTitlePh: "Naam",
    entrySummaryPh: "Samenvatting in één regel",
    entryDetailsPh: "Details, geschiedenis, notities…",
    deleteEntry: "Item verwijderen",
    noWikiEntries: "Nog geen items. Voeg je eerste codex-item toe.",
    searchWiki: "Zoek in de codex…",
    signInRequired: "Meld je aan om deze functie te gebruiken.",
    entrySaved: "Opgeslagen",
    category: "Categorie",
    highlightLore: "Lore-links",
    editMode: "Tekst bewerken",
    loreLinkHint: "Tik op een gemarkeerde naam om de codexkaart te zien.",
    noMatches: "Nog geen codextermen gevonden in deze tekst.",
    openInWiki: "Openen in codex",
    close: "Sluiten",
    write: "Schrijven",
    characters: "Personages",
    timeline: "Tijdlijn",
    lore: "Lore",
    startWriting: "Begin je verhaal…",
    copyText: "Tekst kopiëren",
    copied: "Verhaal gekopieerd naar klembord",
    copyFailed: "Kopiëren mislukt — probeer opnieuw",
    fixGrammar: "Grammatica verbeteren",
    tutAria: "Introductietour",
    tutSkip: "Tour overslaan",
    tutBack: "Terug",
    tutNext: "Volgende",
    tutStart: "Begin met creëren",
    tutWelcomeTitle: "Welkom bij Writer Creator",
    tutWelcomeBody: "Één werkruimte om fictie te schrijven, je personages te ontwerpen, je wereld te tekenen en hoofdstukken te delen met lezers. Hier is een tour van 30 seconden.",
    tutWriterTitle: "Schrijfgereedschap",
    tutWriterBody: "Open Notitieboeken om hoofdstukken te schrijven met automatisch opslaan, personages en lore bij te houden, je tijdlijn te plannen, woorddoelen te stellen en medeauteurs uit te nodigen in de notitieboekchat.",
    tutWikiTitle: "Wereld-wiki & lore-links",
    tutWikiBody: "Bouw een codex van personages, facties, locaties en uitrusting. Tijdens het schrijven worden opgeslagen namen automatisch gemarkeerd — tik erop om de lorekaart te openen zonder de editor te verlaten.",
    tutCanvasTitle: "Tekencanvas",
    tutCanvasBody: "De kunststudio biedt penselen, een vulemmer, lagen, een lijnstabilisator en eigen canvasformaten — perfect voor personageschetsen en strippagina's.",
    tutMapTitle: "Tactische kaart",
    tutMapBody: "In de tactische zandbak kun je een kaart uploaden, terrein schetsen, routepijlen tekenen, gloeiende markers plaatsen, tekstlabels toevoegen en alles met lagen organiseren.",
    nbTitle: "Notitieboeken",
    nbSubtitle: "Privé kladblok met AI-grammaticacorrectie.",
    nbNone: "Nog geen notitieboeken",
    nbNoneHint: "Tik op “Nieuw” om te beginnen.",
    newLabel: "Nieuw",
    phTitle: "Titel",
    deleteNotebook: "Notitieboek verwijderen",
    tNothingToFix: "Nog niets te corrigeren — schrijf eerst iets.",
    tGrammarFail: "Kon de grammatica-assistent niet bereiken.",
    tSignInPost: "Meld je aan om te posten.",
    tSignInSubmit: "Meld je aan om te versturen.",
    tAddTitle: "Voeg eerst een titel toe.",
    tUserNotFound: "Gebruiker niet gevonden.",
    tSubmitted: "Verzonden — het team bekijkt het.",
    sgBugs: "Bugmeldingen",
    sgFeatures: "Functiesuggesties",
    sgMedia: "Video-/mediabugmeldingen",
    sgUser: "Gebruiker melden",
    phSteps: "Stappen om te reproduceren…",
    phIdeaTitle: "Titel van het idee",
    phFeature: "Beschrijf de functie…",
    phWhatBroke: "Wat ging er mis?",
    phContext: "Context (tijdstip, apparaat, enz.)",
    phUsername: "Gebruikersnaam (bv. alice)",
    phWhatHappened: "Wat is er gebeurd? Wees specifiek.",
    tInvalidDims: "Voer geldige afmetingen in.",
    tLayerLimit: "Laaglimiet bereikt (8).",
    tNeedLayer: "Er is minstens één laag nodig.",
    toggleSide: "Zijpaneel wisselen",
    layers: "Lagen",
    addLayer: "Laag toevoegen",
    deleteLayer: "Laag verwijderen",
    actions: "Acties",
    color: "Kleur",
    colorWheel: "Kleurenwiel",
    clearCanvas: "Canvas wissen",
    undo: "Ongedaan maken",
    redo: "Opnieuw",
    undoAria: "Laatste actie ongedaan maken",
    redoAria: "Ongedaan gemaakte actie opnieuw",
    sizeLabel: "Grootte",
    opacityLabel: "Dekking",
    stabilizer: "Stabilisator",
    stabilizerAria: "Sterkte van lijnstabilisator",
    canvasSizeLabel: "Canvasgrootte",
    customLabel: "Aangepast",
    customWidth: "Aangepaste breedte",
    customHeight: "Aangepaste hoogte",
    tImageFail: "Kon die afbeelding niet lezen.",
    tMaxPages: "Max. 30 pagina's per stripbericht.",
    tImageLoadFail: "Een van die afbeeldingen kon niet laden.",
    tAddComicPage: "Voeg minstens één strippagina toe.",
    tWriteSomething: "Schrijf iets of voeg een titel toe.",
    tWordLimit: "Limiet van 500 woorden bereikt.",
    tPosted: "Geplaatst.",
    tSignInReport: "Meld je aan om te melden.",
    tReported: "Gemeld — naar de moderatiewachtrij.",
    tSignInLike: "Meld je aan om te liken.",
    tSignInComment: "Meld je aan om te reageren.",
    searchPh: "Zoek #tags of @gebruikers",
    shareStory: "Deel een verhaal",
    autoSavedDraft: "Automatisch opgeslagen als concept",
    removeImage: "Afbeelding verwijderen",
    removeCover: "Omslag verwijderen",
    linkProject: "Koppel aan een project…",
    removePage: "Pagina verwijderen",
    swipeHint: "Veeg omhoog voor meer verhalen",
    commentsLabel: "Reacties",
    beFirstComment: "Wees de eerste die reageert.",
    addCommentPh: "Voeg een reactie toe…",
    novelTag: "Roman",
    comicTag: "Strip",
    likeLabel: "Vind ik leuk",
    zoomIn: "Inzoomen",
    zoomOut: "Uitzoomen",
    addCharacter: "Personage toevoegen",
    noCharacters: "Nog geen personages.",
    filterByRole: "Filter op tag",
    filterAll: "Alle",
    blankCardWarning: "Maak de lege kaart af voordat je een nieuwe toevoegt.",
    charNamePh: "Naam personage",
  },
  fr: {
    feed: "Fil global",
    notebooks: "Mes carnets privés",
    suggestions: "Boîte à suggestions",
    drawing: "Studio de dessin",
    sandbox: "Bac à sable tactique",
    wiki: "Wiki du monde / Codex",
    settings: "Paramètres",
    jumpToSection: "Aller à une section",
    openMenu: "Ouvrir le menu",
    madeBy: "Créé par",
    account: "Compte",
    signOut: "Se déconnecter",
    signIn: "Se connecter",
    signedInAs: "Connecté en tant que",
    guest: "Navigation en invité",
    language: "Langue",
    languageHint: "Choisissez la langue de l'interface.",
    appearance: "Apparence",
    darkOnly: "Writer Creators utilise un thème studio sombre.",
    wikiSubtitle: "Votre codex de personnages, factions, lieux et équipements.",
    allCategories: "Tout",
    catCharacters: "Personnages",
    catFactions: "Factions",
    catLocations: "Lieux",
    catGear: "Équipement militaire",
    addEntry: "Nouvelle fiche",
    entryTitlePh: "Nom",
    entrySummaryPh: "Résumé en une ligne",
    entryDetailsPh: "Détails, histoire, notes…",
    deleteEntry: "Supprimer la fiche",
    noWikiEntries: "Aucune fiche pour l'instant. Ajoutez votre première fiche.",
    searchWiki: "Rechercher dans le codex…",
    signInRequired: "Connectez-vous pour utiliser cette fonction.",
    entrySaved: "Enregistré",
    category: "Catégorie",
    highlightLore: "Liens du codex",
    editMode: "Modifier le texte",
    loreLinkHint: "Touchez un nom surligné pour voir sa fiche.",
    noMatches: "Aucun terme du codex trouvé dans ce texte.",
    openInWiki: "Ouvrir dans le codex",
    close: "Fermer",
    write: "Écrire",
    characters: "Personnages",
    timeline: "Chronologie",
    lore: "Univers",
    startWriting: "Commencez votre histoire…",
    copyText: "Copier le texte",
    copied: "Histoire copiée dans le presse-papiers",
    copyFailed: "Copie impossible — réessayez",
    fixGrammar: "Corriger la grammaire",
    tutAria: "Visite de démarrage",
    tutSkip: "Passer la visite",
    tutBack: "Retour",
    tutNext: "Suivant",
    tutStart: "Commencer à créer",
    tutWelcomeTitle: "Bienvenue sur Writer Creator",
    tutWelcomeBody: "Un espace unique pour écrire vos fictions, concevoir vos personnages, cartographier votre monde et partager vos chapitres. Voici une visite de 30 secondes.",
    tutWriterTitle: "Outils d'écriture",
    tutWriterBody: "Ouvrez les carnets pour écrire des chapitres avec sauvegarde automatique, suivre personnages et univers, planifier votre chronologie, fixer des objectifs de mots et inviter des collaborateurs au chat du carnet.",
    tutWikiTitle: "Wiki du monde et liens du codex",
    tutWikiBody: "Créez un codex de personnages, factions, lieux et équipements. Pendant l'écriture, les noms enregistrés sont surlignés automatiquement — touchez-en un pour ouvrir sa fiche sans quitter l'éditeur.",
    tutCanvasTitle: "Toile de dessin",
    tutCanvasBody: "Le studio d'art offre des pinceaux, un pot de peinture, des calques, un stabilisateur de tracé et des tailles de toile personnalisées — parfait pour les croquis et les planches de BD.",
    tutMapTitle: "Carte tactique",
    tutMapBody: "Dans le bac à sable tactique, importez une carte, esquissez le terrain, tracez des flèches d'itinéraire, posez des marqueurs lumineux, ajoutez des étiquettes et organisez le tout en calques.",
    nbTitle: "Carnets",
    nbSubtitle: "Bloc-notes privé avec correction grammaticale IA.",
    nbNone: "Aucun carnet pour l'instant",
    nbNoneHint: "Appuyez sur « Nouveau » pour commencer.",
    newLabel: "Nouveau",
    phTitle: "Titre",
    deleteNotebook: "Supprimer le carnet",
    tNothingToFix: "Rien à corriger — écrivez d'abord quelque chose.",
    tGrammarFail: "Impossible de joindre l'assistant grammatical.",
    tSignInPost: "Connectez-vous pour publier.",
    tSignInSubmit: "Connectez-vous pour envoyer.",
    tAddTitle: "Ajoutez d'abord un titre.",
    tUserNotFound: "Utilisateur introuvable.",
    tSubmitted: "Envoyé — l'équipe va l'examiner.",
    sgBugs: "Rapports de bugs",
    sgFeatures: "Suggestions de fonctionnalités",
    sgMedia: "Bugs vidéo / médias",
    sgUser: "Signaler un utilisateur",
    phSteps: "Étapes pour reproduire…",
    phIdeaTitle: "Titre de l'idée",
    phFeature: "Décrivez la fonctionnalité…",
    phWhatBroke: "Qu'est-ce qui a cassé ?",
    phContext: "Contexte (horodatage, appareil, etc.)",
    phUsername: "Nom d'utilisateur (ex. alice)",
    phWhatHappened: "Que s'est-il passé ? Soyez précis.",
    tInvalidDims: "Entrez des dimensions valides.",
    tLayerLimit: "Limite de calques atteinte (8).",
    tNeedLayer: "Au moins un calque est requis.",
    toggleSide: "Afficher/masquer le panneau",
    layers: "Calques",
    addLayer: "Ajouter un calque",
    deleteLayer: "Supprimer le calque",
    actions: "Actions",
    color: "Couleur",
    colorWheel: "Roue chromatique",
    clearCanvas: "Effacer la toile",
    undo: "Annuler",
    redo: "Rétablir",
    undoAria: "Annuler la dernière action",
    redoAria: "Rétablir la dernière action annulée",
    sizeLabel: "Taille",
    opacityLabel: "Opacité",
    stabilizer: "Stabilisateur",
    stabilizerAria: "Force du stabilisateur de trait",
    canvasSizeLabel: "Taille de la toile",
    customLabel: "Personnalisé",
    customWidth: "Largeur personnalisée",
    customHeight: "Hauteur personnalisée",
    tImageFail: "Impossible de lire cette image.",
    tMaxPages: "30 pages max par publication BD.",
    tImageLoadFail: "Une de ces images n'a pas pu être chargée.",
    tAddComicPage: "Ajoutez au moins une page de BD.",
    tWriteSomething: "Écrivez quelque chose ou ajoutez un titre.",
    tWordLimit: "Limite de 500 mots atteinte.",
    tPosted: "Publié.",
    tSignInReport: "Connectez-vous pour signaler.",
    tReported: "Signalé — envoyé à la modération.",
    tSignInLike: "Connectez-vous pour aimer.",
    tSignInComment: "Connectez-vous pour commenter.",
    searchPh: "Rechercher #tags ou @utilisateurs",
    shareStory: "Partager une histoire",
    autoSavedDraft: "Enregistré automatiquement en brouillon",
    removeImage: "Supprimer l'image",
    removeCover: "Supprimer la couverture",
    linkProject: "Lier à un projet…",
    removePage: "Supprimer la page",
    swipeHint: "Balayez vers le haut pour explorer",
    commentsLabel: "Commentaires",
    beFirstComment: "Soyez le premier à commenter.",
    addCommentPh: "Ajouter un commentaire…",
    novelTag: "Roman",
    comicTag: "BD",
    likeLabel: "J'aime",
    zoomIn: "Zoom avant",
    zoomOut: "Zoom arrière",
    addCharacter: "Ajouter un personnage",
    noCharacters: "Aucun personnage pour l'instant.",
    filterByRole: "Filtrer par tag",
    filterAll: "Tous",
    blankCardWarning: "Terminez la fiche vide avant d'en ajouter une autre.",
    charNamePh: "Nom du personnage",
  },
  es: {
    feed: "Feed global",
    notebooks: "Mis cuadernos privados",
    suggestions: "Buzón de sugerencias",
    drawing: "Estudio de dibujo",
    sandbox: "Arenero táctico",
    wiki: "Wiki del mundo / Códice",
    settings: "Ajustes",
    jumpToSection: "Ir a una sección",
    openMenu: "Abrir menú",
    madeBy: "Hecho por",
    account: "Cuenta",
    signOut: "Cerrar sesión",
    signIn: "Iniciar sesión",
    signedInAs: "Sesión iniciada como",
    guest: "Navegando como invitado",
    language: "Idioma",
    languageHint: "Elige el idioma de la interfaz.",
    appearance: "Apariencia",
    darkOnly: "Writer Creators usa un tema de estudio oscuro.",
    wikiSubtitle: "Tu códice de personajes, facciones, lugares y equipo.",
    allCategories: "Todo",
    catCharacters: "Personajes",
    catFactions: "Facciones",
    catLocations: "Lugares",
    catGear: "Equipo militar",
    addEntry: "Nueva entrada",
    entryTitlePh: "Nombre",
    entrySummaryPh: "Resumen en una línea",
    entryDetailsPh: "Detalles, historia, notas…",
    deleteEntry: "Eliminar entrada",
    noWikiEntries: "Aún no hay entradas. Añade tu primera entrada del códice.",
    searchWiki: "Buscar en el códice…",
    signInRequired: "Inicia sesión para usar esta función.",
    entrySaved: "Guardado",
    category: "Categoría",
    highlightLore: "Enlaces del códice",
    editMode: "Editar texto",
    loreLinkHint: "Toca un nombre resaltado para ver su ficha.",
    noMatches: "Aún no se encontraron términos del códice en este texto.",
    openInWiki: "Abrir en el códice",
    close: "Cerrar",
    write: "Escribir",
    characters: "Personajes",
    timeline: "Cronología",
    lore: "Trasfondo",
    startWriting: "Empieza tu historia…",
    copyText: "Copiar texto",
    copied: "Historia copiada al portapapeles",
    copyFailed: "No se pudo copiar — inténtalo de nuevo",
    fixGrammar: "Corregir gramática",
    tutAria: "Tour de inicio",
    tutSkip: "Omitir tour",
    tutBack: "Atrás",
    tutNext: "Siguiente",
    tutStart: "Empezar a crear",
    tutWelcomeTitle: "Bienvenido a Writer Creator",
    tutWelcomeBody: "Un único espacio para escribir ficción, diseñar tu reparto, cartografiar tu mundo y compartir capítulos con lectores. Aquí tienes un tour de 30 segundos.",
    tutWriterTitle: "Herramientas de escritura",
    tutWriterBody: "Abre los cuadernos para escribir capítulos con autoguardado, gestionar personajes y trasfondo, planificar tu cronología, fijar metas de palabras e invitar colaboradores al chat del cuaderno.",
    tutWikiTitle: "Wiki del mundo y enlaces de trasfondo",
    tutWikiBody: "Crea un códice de personajes, facciones, lugares y equipo. Al escribir, los nombres guardados se resaltan automáticamente: tócalos para abrir su ficha sin salir del editor.",
    tutCanvasTitle: "Lienzo de dibujo",
    tutCanvasBody: "El estudio de arte ofrece pinceles, cubo de pintura, capas, estabilizador de trazo y tamaños de lienzo personalizados — ideal para bocetos y páginas de cómic.",
    tutMapTitle: "Mapa táctico",
    tutMapBody: "En el arenero táctico puedes subir un mapa, dibujar terreno, trazar flechas de ruta, colocar marcadores brillantes, añadir etiquetas y organizarlo todo con capas.",
    nbTitle: "Cuadernos",
    nbSubtitle: "Borrador privado con corrección gramatical por IA.",
    nbNone: "Aún no hay cuadernos",
    nbNoneHint: "Toca «Nuevo» para empezar.",
    newLabel: "Nuevo",
    phTitle: "Título",
    deleteNotebook: "Eliminar cuaderno",
    tNothingToFix: "Nada que corregir: escribe algo primero.",
    tGrammarFail: "No se pudo contactar al asistente gramatical.",
    tSignInPost: "Inicia sesión para publicar.",
    tSignInSubmit: "Inicia sesión para enviar.",
    tAddTitle: "Añade un título primero.",
    tUserNotFound: "Usuario no encontrado.",
    tSubmitted: "Enviado: el equipo lo revisará.",
    sgBugs: "Informes de errores",
    sgFeatures: "Sugerencias de funciones",
    sgMedia: "Errores de vídeo/medios",
    sgUser: "Denunciar a un usuario",
    phSteps: "Pasos para reproducirlo…",
    phIdeaTitle: "Título de la idea",
    phFeature: "Describe la función…",
    phWhatBroke: "¿Qué falló?",
    phContext: "Contexto (marca de tiempo, dispositivo, etc.)",
    phUsername: "Nombre de usuario (p. ej. alice)",
    phWhatHappened: "¿Qué ocurrió? Sé específico.",
    tInvalidDims: "Introduce dimensiones válidas.",
    tLayerLimit: "Límite de capas alcanzado (8).",
    tNeedLayer: "Se necesita al menos una capa.",
    toggleSide: "Mostrar u ocultar el panel",
    layers: "Capas",
    addLayer: "Añadir capa",
    deleteLayer: "Eliminar capa",
    actions: "Acciones",
    color: "Color",
    colorWheel: "Rueda de color",
    clearCanvas: "Limpiar lienzo",
    undo: "Deshacer",
    redo: "Rehacer",
    undoAria: "Deshacer la última acción",
    redoAria: "Rehacer la última acción deshecha",
    sizeLabel: "Tamaño",
    opacityLabel: "Opacidad",
    stabilizer: "Estabilizador",
    stabilizerAria: "Intensidad del estabilizador de trazo",
    canvasSizeLabel: "Tamaño del lienzo",
    customLabel: "Personalizado",
    customWidth: "Ancho personalizado",
    customHeight: "Alto personalizado",
    tImageFail: "No se pudo leer esa imagen.",
    tMaxPages: "Máximo 30 páginas por cómic.",
    tImageLoadFail: "Una de esas imágenes no se cargó.",
    tAddComicPage: "Añade al menos una página de cómic.",
    tWriteSomething: "Escribe algo o añade un título.",
    tWordLimit: "Límite de 500 palabras alcanzado.",
    tPosted: "Publicado.",
    tSignInReport: "Inicia sesión para denunciar.",
    tReported: "Denunciado: enviado a moderación.",
    tSignInLike: "Inicia sesión para dar me gusta.",
    tSignInComment: "Inicia sesión para comentar.",
    searchPh: "Buscar #etiquetas o @usuarios",
    shareStory: "Comparte una historia",
    autoSavedDraft: "Guardado automáticamente como borrador",
    removeImage: "Quitar imagen",
    removeCover: "Quitar portada",
    linkProject: "Vincular a un proyecto…",
    removePage: "Quitar página",
    swipeHint: "Desliza hacia arriba para explorar",
    commentsLabel: "Comentarios",
    beFirstComment: "Sé el primero en comentar.",
    addCommentPh: "Añadir un comentario…",
    novelTag: "Novela",
    comicTag: "Cómic",
    likeLabel: "Me gusta",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    addCharacter: "A\u00f1adir personaje",
    noCharacters: "A\u00fan no hay personajes.",
    filterByRole: "Filtrar por etiqueta",
    filterAll: "Todos",
    blankCardWarning: "Completa la tarjeta vac\u00eda antes de a\u00f1adir otra.",
    charNamePh: "Nombre del personaje",
  },
  pt: {
    feed: "Feed global",
    notebooks: "Meus cadernos privados",
    suggestions: "Caixa de sugestões",
    drawing: "Estúdio de desenho",
    sandbox: "Caixa de areia tática",
    wiki: "Wiki do mundo / Códice",
    settings: "Configurações",
    jumpToSection: "Ir para uma seção",
    openMenu: "Abrir menu",
    madeBy: "Feito por",
    account: "Conta",
    signOut: "Sair",
    signIn: "Entrar",
    signedInAs: "Conectado como",
    guest: "Navegando como visitante",
    language: "Idioma",
    languageHint: "Escolha o idioma da interface.",
    appearance: "Aparência",
    darkOnly: "Writer Creators usa um tema de estúdio escuro.",
    wikiSubtitle: "Seu códice de personagens, facções, locais e equipamentos.",
    allCategories: "Tudo",
    catCharacters: "Personagens",
    catFactions: "Facções",
    catLocations: "Locais",
    catGear: "Equipamento militar",
    addEntry: "Nova entrada",
    entryTitlePh: "Nome",
    entrySummaryPh: "Resumo em uma linha",
    entryDetailsPh: "Detalhes, história, notas…",
    deleteEntry: "Excluir entrada",
    noWikiEntries: "Nenhuma entrada ainda. Adicione a primeira do seu códice.",
    searchWiki: "Pesquisar no códice…",
    signInRequired: "Entre para usar este recurso.",
    entrySaved: "Salvo",
    category: "Categoria",
    highlightLore: "Links do códice",
    editMode: "Editar texto",
    loreLinkHint: "Toque num nome destacado para ver a ficha dele.",
    noMatches: "Nenhum termo do códice encontrado neste texto ainda.",
    openInWiki: "Abrir no códice",
    close: "Fechar",
    write: "Escrever",
    characters: "Personagens",
    timeline: "Linha do tempo",
    lore: "Universo",
    startWriting: "Comece a sua história…",
    copyText: "Copiar texto",
    copied: "História copiada para a área de transferência",
    copyFailed: "Não foi possível copiar — tente novamente",
    fixGrammar: "Corrigir gramática",
    tutAria: "Tour inicial",
    tutSkip: "Pular tour",
    tutBack: "Voltar",
    tutNext: "Próximo",
    tutStart: "Começar a criar",
    tutWelcomeTitle: "Bem-vindo ao Writer Creator",
    tutWelcomeBody: "Um espaço único para escrever ficção, criar seu elenco, mapear seu mundo e compartilhar capítulos com leitores. Veja um tour de 30 segundos.",
    tutWriterTitle: "Ferramentas de escrita",
    tutWriterBody: "Abra os cadernos para escrever capítulos com salvamento automático, acompanhar personagens e universo, planejar sua linha do tempo, definir metas de palavras e convidar colaboradores para o chat do caderno.",
    tutWikiTitle: "Wiki do mundo e links de universo",
    tutWikiBody: "Monte um códice de personagens, facções, locais e equipamentos. Ao escrever, os nomes salvos são destacados automaticamente — toque num deles para abrir a ficha sem sair do editor.",
    tutCanvasTitle: "Tela de desenho",
    tutCanvasBody: "O estúdio de arte oferece pincéis, balde de tinta, camadas, estabilizador de traço e tamanhos de tela personalizados — perfeito para esboços e páginas de quadrinhos.",
    tutMapTitle: "Mapa tático",
    tutMapBody: "Na caixa de areia tática você pode enviar um mapa, esboçar terreno, desenhar setas de rota, colocar marcadores brilhantes, adicionar rótulos e organizar tudo em camadas.",
    nbTitle: "Cadernos",
    nbSubtitle: "Rascunho privado com correção gramatical por IA.",
    nbNone: "Ainda sem cadernos",
    nbNoneHint: "Toque em “Novo” para começar.",
    newLabel: "Novo",
    phTitle: "Título",
    deleteNotebook: "Excluir caderno",
    tNothingToFix: "Nada para corrigir — escreva algo primeiro.",
    tGrammarFail: "Não foi possível contactar o assistente gramatical.",
    tSignInPost: "Entre para publicar.",
    tSignInSubmit: "Entre para enviar.",
    tAddTitle: "Adicione um título primeiro.",
    tUserNotFound: "Utilizador não encontrado.",
    tSubmitted: "Enviado — a equipa vai analisar.",
    sgBugs: "Relatórios de erros",
    sgFeatures: "Sugestões de funcionalidades",
    sgMedia: "Erros de vídeo/mídia",
    sgUser: "Denunciar um utilizador",
    phSteps: "Passos para reproduzir…",
    phIdeaTitle: "Título da ideia",
    phFeature: "Descreva a funcionalidade…",
    phWhatBroke: "O que falhou?",
    phContext: "Contexto (data/hora, dispositivo, etc.)",
    phUsername: "Nome de utilizador (ex.: alice)",
    phWhatHappened: "O que aconteceu? Seja específico.",
    tInvalidDims: "Insira dimensões válidas.",
    tLayerLimit: "Limite de camadas atingido (8).",
    tNeedLayer: "É necessária pelo menos uma camada.",
    toggleSide: "Mostrar/ocultar painel lateral",
    layers: "Camadas",
    addLayer: "Adicionar camada",
    deleteLayer: "Excluir camada",
    actions: "Ações",
    color: "Cor",
    colorWheel: "Roda de cores",
    clearCanvas: "Limpar tela",
    undo: "Desfazer",
    redo: "Refazer",
    undoAria: "Desfazer a última ação",
    redoAria: "Refazer a última ação desfeita",
    sizeLabel: "Tamanho",
    opacityLabel: "Opacidade",
    stabilizer: "Estabilizador",
    stabilizerAria: "Força do estabilizador de traço",
    canvasSizeLabel: "Tamanho da tela",
    customLabel: "Personalizado",
    customWidth: "Largura personalizada",
    customHeight: "Altura personalizada",
    tImageFail: "Não foi possível ler essa imagem.",
    tMaxPages: "Máximo de 30 páginas por banda desenhada.",
    tImageLoadFail: "Uma dessas imagens não carregou.",
    tAddComicPage: "Adicione pelo menos uma página.",
    tWriteSomething: "Escreva algo ou adicione um título.",
    tWordLimit: "Limite de 500 palavras atingido.",
    tPosted: "Publicado.",
    tSignInReport: "Entre para denunciar.",
    tReported: "Denunciado — enviado à moderação.",
    tSignInLike: "Entre para curtir.",
    tSignInComment: "Entre para comentar.",
    searchPh: "Pesquisar #tags ou @utilizadores",
    shareStory: "Partilhe uma história",
    autoSavedDraft: "Guardado automaticamente como rascunho",
    removeImage: "Remover imagem",
    removeCover: "Remover capa",
    linkProject: "Ligar a um projeto…",
    removePage: "Remover página",
    swipeHint: "Deslize para cima para explorar",
    commentsLabel: "Comentários",
    beFirstComment: "Seja o primeiro a comentar.",
    addCommentPh: "Adicionar um comentário…",
    novelTag: "Romance",
    comicTag: "Banda desenhada",
    likeLabel: "Curtir",
    zoomIn: "Ampliar",
    zoomOut: "Reduzir",
    addCharacter: "Adicionar personagem",
    noCharacters: "Nenhum personagem ainda.",
    filterByRole: "Filtrar por tag",
    filterAll: "Todos",
    blankCardWarning: "Conclua o cart\u00e3o vazio antes de adicionar outro.",
    charNamePh: "Nome do personagem",
  },
  ar: {
    feed: "الموجز العام",
    notebooks: "دفاتري الخاصة",
    suggestions: "صندوق الاقتراحات",
    drawing: "استوديو الرسم",
    sandbox: "الساحة التكتيكية",
    wiki: "موسوعة العالم / الكودكس",
    settings: "الإعدادات",
    jumpToSection: "الانتقال إلى قسم",
    openMenu: "فتح القائمة",
    madeBy: "من إعداد",
    account: "الحساب",
    signOut: "تسجيل الخروج",
    signIn: "تسجيل الدخول",
    signedInAs: "مسجّل الدخول باسم",
    guest: "تتصفح كزائر",
    language: "اللغة",
    languageHint: "اختر لغة واجهة التطبيق.",
    appearance: "المظهر",
    darkOnly: "يستخدم Writer Creators مظهرًا داكنًا.",
    wikiSubtitle: "موسوعتك للشخصيات والفصائل والأماكن والعتاد.",
    allCategories: "الكل",
    catCharacters: "الشخصيات",
    catFactions: "الفصائل",
    catLocations: "الأماكن",
    catGear: "العتاد العسكري",
    addEntry: "مدخل جديد",
    entryTitlePh: "الاسم",
    entrySummaryPh: "ملخص في سطر واحد",
    entryDetailsPh: "التفاصيل والتاريخ والملاحظات…",
    deleteEntry: "حذف المدخل",
    noWikiEntries: "لا مداخل بعد. أضف أول مدخل في موسوعتك.",
    searchWiki: "ابحث في الموسوعة…",
    signInRequired: "سجّل الدخول لاستخدام هذه الميزة.",
    entrySaved: "تم الحفظ",
    category: "الفئة",
    highlightLore: "روابط الموسوعة",
    editMode: "تحرير النص",
    loreLinkHint: "اضغط على اسم مُبرز لعرض بطاقته.",
    noMatches: "لم يتم العثور على مصطلحات من الموسوعة في هذا النص بعد.",
    openInWiki: "فتح في الموسوعة",
    close: "إغلاق",
    write: "الكتابة",
    characters: "الشخصيات",
    timeline: "الخط الزمني",
    lore: "خلفية العالم",
    startWriting: "ابدأ كتابة قصتك…",
    copyText: "نسخ النص",
    copied: "تم نسخ القصة إلى الحافظة",
    copyFailed: "تعذّر النسخ — حاول مرة أخرى",
    fixGrammar: "تصحيح القواعد",
    tutAria: "جولة البداية",
    tutSkip: "تخطي الجولة",
    tutBack: "رجوع",
    tutNext: "التالي",
    tutStart: "ابدأ الإبداع",
    tutWelcomeTitle: "مرحبًا بك في Writer Creator",
    tutWelcomeBody: "مساحة واحدة لكتابة القصص وتصميم شخصياتك ورسم خريطة عالمك ومشاركة الفصول مع القراء. إليك جولة من 30 ثانية.",
    tutWriterTitle: "أدوات الكتابة",
    tutWriterBody: "افتح الدفاتر لكتابة الفصول مع الحفظ التلقائي، وتتبع الشخصيات وخلفية العالم، وتخطيط الخط الزمني، وتحديد أهداف الكلمات، ودعوة المتعاونين إلى دردشة الدفتر.",
    tutWikiTitle: "موسوعة العالم وروابط الخلفية",
    tutWikiBody: "ابنِ موسوعة للشخصيات والفصائل والأماكن والعتاد. أثناء الكتابة تُبرز الأسماء المحفوظة تلقائيًا — اضغط على أحدها لعرض بطاقتها دون مغادرة المحرر.",
    tutCanvasTitle: "لوحة الرسم",
    tutCanvasBody: "يمنحك استوديو الفن فرشًا ودلو تلوين وطبقات ومثبّت خطوط وأحجام لوحات مخصصة — مثالي لرسم الشخصيات وصفحات القصص المصورة.",
    tutMapTitle: "الخريطة التكتيكية",
    tutMapBody: "في الساحة التكتيكية يمكنك تحميل خريطة ورسم التضاريس ورسم أسهم المسارات ووضع علامات متوهجة وإضافة نصوص وتنظيم كل شيء بالطبقات.",
    nbTitle: "الدفاتر",
    nbSubtitle: "مسوّدة خاصة مع تصحيح نحوي بالذكاء الاصطناعي.",
    nbNone: "لا توجد دفاتر بعد",
    nbNoneHint: "اضغط على «جديد» للبدء.",
    newLabel: "جديد",
    phTitle: "العنوان",
    deleteNotebook: "حذف الدفتر",
    tNothingToFix: "لا يوجد ما يُصحّح بعد — اكتب شيئًا أولًا.",
    tGrammarFail: "تعذّر الوصول إلى مساعد القواعد.",
    tSignInPost: "سجّل الدخول للنشر.",
    tSignInSubmit: "سجّل الدخول للإرسال.",
    tAddTitle: "أضف عنوانًا أولًا.",
    tUserNotFound: "المستخدم غير موجود.",
    tSubmitted: "تم الإرسال — سيراجعه الفريق.",
    sgBugs: "تقارير الأخطاء",
    sgFeatures: "اقتراحات الميزات",
    sgMedia: "تقارير أخطاء الفيديو والوسائط",
    sgUser: "الإبلاغ عن مستخدم",
    phSteps: "خطوات إعادة الإنتاج…",
    phIdeaTitle: "عنوان الفكرة",
    phFeature: "اوصف الميزة…",
    phWhatBroke: "ما الذي تعطّل؟",
    phContext: "السياق (الوقت، الجهاز، إلخ)",
    phUsername: "اسم المستخدم (مثال: alice)",
    phWhatHappened: "ماذا حدث؟ كن محددًا.",
    tInvalidDims: "أدخل أبعادًا صحيحة.",
    tLayerLimit: "تم الوصول إلى حد الطبقات (8).",
    tNeedLayer: "يجب وجود طبقة واحدة على الأقل.",
    toggleSide: "إظهار/إخفاء اللوحة الجانبية",
    layers: "الطبقات",
    addLayer: "إضافة طبقة",
    deleteLayer: "حذف الطبقة",
    actions: "الإجراءات",
    color: "اللون",
    colorWheel: "دائرة الألوان",
    clearCanvas: "تفريغ اللوحة",
    undo: "تراجع",
    redo: "إعادة",
    undoAria: "التراجع عن الإجراء الأخير",
    redoAria: "إعادة الإجراء الذي تم التراجع عنه",
    sizeLabel: "الحجم",
    opacityLabel: "الشفافية",
    stabilizer: "المثبّت",
    stabilizerAria: "قوة مثبّت الخط",
    canvasSizeLabel: "حجم اللوحة",
    customLabel: "مخصص",
    customWidth: "عرض مخصص",
    customHeight: "ارتفاع مخصص",
    tImageFail: "تعذّر قراءة هذه الصورة.",
    tMaxPages: "بحد أقصى 30 صفحة لكل منشور مصوّر.",
    tImageLoadFail: "فشل تحميل إحدى الصور.",
    tAddComicPage: "أضف صفحة مصوّرة واحدة على الأقل.",
    tWriteSomething: "اكتب شيئًا أو أضف عنوانًا.",
    tWordLimit: "تم الوصول إلى حد 500 كلمة.",
    tPosted: "تم النشر.",
    tSignInReport: "سجّل الدخول للإبلاغ.",
    tReported: "تم الإبلاغ — أُرسل إلى فريق الإشراف.",
    tSignInLike: "سجّل الدخول للإعجاب.",
    tSignInComment: "سجّل الدخول للتعليق.",
    searchPh: "ابحث عن #وسوم أو @مستخدمين",
    shareStory: "شارك قصة",
    autoSavedDraft: "تم الحفظ تلقائيًا كمسوّدة",
    removeImage: "إزالة الصورة",
    removeCover: "إزالة الغلاف",
    linkProject: "اربط بمشروع…",
    removePage: "إزالة الصفحة",
    swipeHint: "اسحب للأعلى لاستكشاف القصص",
    commentsLabel: "التعليقات",
    beFirstComment: "كن أول من يعلّق.",
    addCommentPh: "أضف تعليقًا…",
    novelTag: "رواية",
    comicTag: "مصوّرة",
    likeLabel: "إعجاب",
    zoomIn: "تكبير",
    zoomOut: "تصغير",
    addCharacter: "\u0625\u0636\u0627\u0641\u0629 \u0634\u062e\u0635\u064a\u0629",
    noCharacters: "\u0644\u0627 \u062a\u0648\u062c\u062f \u0634\u062e\u0635\u064a\u0627\u062a \u0628\u0639\u062f.",
    filterByRole: "\u062a\u0635\u0641\u064a\u0629 \u0628\u0627\u0644\u0648\u0633\u0645",
    filterAll: "\u0627\u0644\u0643\u0644",
    blankCardWarning: "\u0623\u0643\u0645\u0644 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0627\u0631\u063a\u0629 \u0642\u0628\u0644 \u0625\u0636\u0627\u0641\u0629 \u0623\u062e\u0631\u0649.",
    charNamePh: "\u0627\u0633\u0645 \u0627\u0644\u0634\u062e\u0635\u064a\u0629",
  },
  zh: {
    feed: "全球动态",
    notebooks: "我的私人笔记本",
    suggestions: "建议箱",
    drawing: "绘画工作室",
    sandbox: "战术沙盘",
    wiki: "世界百科 / 图鉴",
    settings: "设置",
    jumpToSection: "跳转到板块",
    openMenu: "打开菜单",
    madeBy: "制作者",
    account: "账户",
    signOut: "退出登录",
    signIn: "登录",
    signedInAs: "已登录：",
    guest: "以访客身份浏览",
    language: "语言",
    languageHint: "选择应用界面语言。",
    appearance: "外观",
    darkOnly: "Writer Creators 使用深色工作室主题。",
    wikiSubtitle: "你的角色、势力、地点与装备图鉴。",
    allCategories: "全部",
    catCharacters: "角色",
    catFactions: "势力",
    catLocations: "地点",
    catGear: "军事装备",
    addEntry: "新建条目",
    entryTitlePh: "名称",
    entrySummaryPh: "一句话简介",
    entryDetailsPh: "详细内容、历史、备注…",
    deleteEntry: "删除条目",
    noWikiEntries: "还没有条目。添加第一个图鉴条目。",
    searchWiki: "搜索图鉴…",
    signInRequired: "登录后即可使用此功能。",
    entrySaved: "已保存",
    category: "分类",
    highlightLore: "设定链接",
    editMode: "编辑文本",
    loreLinkHint: "点击高亮的名称即可查看图鉴卡片。",
    noMatches: "此文本中尚未发现图鉴词条。",
    openInWiki: "在图鉴中打开",
    close: "关闭",
    write: "写作",
    characters: "角色",
    timeline: "时间线",
    lore: "设定",
    startWriting: "开始写你的故事…",
    copyText: "复制文本",
    copied: "故事已复制到剪贴板",
    copyFailed: "复制失败——请重试",
    fixGrammar: "修正语法",
    tutAria: "新手导览",
    tutSkip: "跳过导览",
    tutBack: "上一步",
    tutNext: "下一步",
    tutStart: "开始创作",
    tutWelcomeTitle: "欢迎使用 Writer Creator",
    tutWelcomeBody: "一个集写作、角色设计、世界地图与章节分享于一体的工作空间。这是一段 30 秒的导览。",
    tutWriterTitle: "写作工具",
    tutWriterBody: "打开笔记本即可自动保存地撰写章节、管理角色与设定、规划时间线、设定字数目标，并邀请协作者加入笔记本聊天。",
    tutWikiTitle: "世界百科与设定链接",
    tutWikiBody: "建立角色、势力、地点与装备的图鉴。写作时已保存的名称会自动高亮——点击即可在不离开编辑器的情况下查看设定卡片。",
    tutCanvasTitle: "绘画画布",
    tutCanvasBody: "艺术工作室提供画笔、油漆桶、图层、笔迹稳定器和自定义画布尺寸——非常适合角色草图与漫画页面。",
    tutMapTitle: "战术地图",
    tutMapBody: "在战术沙盘中，你可以上传地图、勾画地形、绘制路线箭头、放置发光标记、添加文字标签，并用图层进行整理。",
    nbTitle: "笔记本",
    nbSubtitle: "私人草稿本，配备 AI 语法修正。",
    nbNone: "还没有笔记本",
    nbNoneHint: "点击“新建”开始。",
    newLabel: "新建",
    phTitle: "标题",
    deleteNotebook: "删除笔记本",
    tNothingToFix: "暂无内容可修正——请先写点东西。",
    tGrammarFail: "无法连接语法助手。",
    tSignInPost: "登录后才能发布。",
    tSignInSubmit: "请登录后提交。",
    tAddTitle: "请先添加标题。",
    tUserNotFound: "未找到该用户。",
    tSubmitted: "已提交——工作人员将审核。",
    sgBugs: "错误报告",
    sgFeatures: "功能建议",
    sgMedia: "视频/媒体错误报告",
    sgUser: "举报用户",
    phSteps: "复现步骤…",
    phIdeaTitle: "想法标题",
    phFeature: "描述该功能…",
    phWhatBroke: "出了什么问题？",
    phContext: "上下文（时间点、设备等）",
    phUsername: "用户名（例如 alice）",
    phWhatHappened: "发生了什么？请具体说明。",
    tInvalidDims: "请输入有效尺寸。",
    tLayerLimit: "已达图层上限（8）。",
    tNeedLayer: "至少需要一个图层。",
    toggleSide: "切换侧边面板",
    layers: "图层",
    addLayer: "添加图层",
    deleteLayer: "删除图层",
    actions: "操作",
    color: "颜色",
    colorWheel: "色轮",
    clearCanvas: "清空画布",
    undo: "撤销",
    redo: "重做",
    undoAria: "撤销上一步操作",
    redoAria: "重做上一步撤销的操作",
    sizeLabel: "大小",
    opacityLabel: "不透明度",
    stabilizer: "稳定器",
    stabilizerAria: "笔迹稳定器强度",
    canvasSizeLabel: "画布尺寸",
    customLabel: "自定义",
    customWidth: "自定义宽度",
    customHeight: "自定义高度",
    tImageFail: "无法读取该图片。",
    tMaxPages: "每篇漫画最多 30 页。",
    tImageLoadFail: "其中一张图片加载失败。",
    tAddComicPage: "请至少添加一页漫画。",
    tWriteSomething: "请写点内容或添加标题。",
    tWordLimit: "已达 500 字上限。",
    tPosted: "已发布。",
    tSignInReport: "登录后才能举报。",
    tReported: "已举报——已发送给审核队列。",
    tSignInLike: "登录后才能点赞。",
    tSignInComment: "登录后才能评论。",
    searchPh: "搜索 #标签 或 @用户",
    shareStory: "分享故事",
    autoSavedDraft: "已自动保存为草稿",
    removeImage: "移除图片",
    removeCover: "移除封面",
    linkProject: "关联到项目…",
    removePage: "移除页面",
    swipeHint: "上滑浏览故事",
    commentsLabel: "评论",
    beFirstComment: "来发表第一条评论。",
    addCommentPh: "添加评论…",
    novelTag: "小说",
    comicTag: "漫画",
    likeLabel: "点赞",
    zoomIn: "放大",
    zoomOut: "缩小",
    addCharacter: "\u6dfb\u52a0\u89d2\u8272",
    noCharacters: "\u8fd8\u6ca1\u6709\u89d2\u8272\u3002",
    filterByRole: "\u6309\u6807\u7b7e\u7b5b\u9009",
    filterAll: "\u5168\u90e8",
    blankCardWarning: "\u8bf7\u5148\u5b8c\u6210\u7a7a\u767d\u5361\u7247\u518d\u6dfb\u52a0\u65b0\u7684\u3002",
    charNamePh: "\u89d2\u8272\u540d\u79f0",
  },
};

type Ctx = { lang: LangCode; setLang: (l: LangCode) => void; t: (k: Key) => string };
const LanguageContext = createContext<Ctx | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => {
    if (typeof window === "undefined") return "en";
    try {
      const saved = window.localStorage.getItem("dd:lang") as LangCode | null;
      if (saved && LANGUAGES.some((l) => l.code === saved)) return saved;
    } catch {}
    return "en";
  });

  useEffect(() => {
    try {
      const saved = window.localStorage.getItem("dd:lang") as LangCode | null;
      if (saved && LANGUAGES.some((l) => l.code === saved)) setLangState(saved);
    } catch {}
  }, []);

  useEffect(() => {
    if (typeof document === "undefined") return;
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, [lang]);

  const setLang = (l: LangCode) => {
    setLangState(l);
    try { window.localStorage.setItem("dd:lang", l); } catch {}
  };

  // Explicit English fallback: a missing or blank translation never renders empty.
  const t = (k: Key) => {
    const v = DICT[lang]?.[k];
    if (typeof v === "string" && v.trim().length > 0) return v;
    return en[k] ?? String(k);
  };

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) return { lang: "en" as LangCode, setLang: () => {}, t: (k: Key) => en[k] ?? String(k) };
  return ctx;
}
