import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export const LANGUAGES = [
  { code: "en", label: "English", native: "English" },
  { code: "de", label: "German", native: "Deutsch" },
  { code: "nl", label: "Dutch", native: "Nederlands" },
  { code: "fr", label: "French", native: "Français" },
  { code: "es", label: "Spanish", native: "Español" },
  { code: "pt", label: "Portuguese", native: "Português" },
  { code: "ar", label: "Arabic", native: "العربية" },
  { code: "zh", label: "Mandarin", native: "中文" },
] as const;

export type LangCode = (typeof LANGUAGES)[number]["code"];

const en = {
  // Sections / navigation
  feed: "Global Feed",
  notebooks: "My Private Notebooks",
  suggestions: "Suggestions Box",
  drawing: "Drawing Studio",
  sandbox: "Tactical Sandbox",
  wiki: "World Wiki / Codex",
  settings: "Settings",
  jumpToSection: "Jump to a section",
  openMenu: "Open menu",
  madeBy: "Made by",

  // Settings
  account: "Account",
  signOut: "Sign out",
  signIn: "Sign in",
  signedInAs: "Signed in as",
  guest: "Browsing as guest",
  language: "Language",
  languageHint: "Choose the language for the app interface.",
  appearance: "Appearance",
  darkOnly: "Writer Creators uses a dark studio theme.",

  // World Wiki
  wikiSubtitle: "Your codex of characters, factions, locations and gear.",
  allCategories: "All",
  catCharacters: "Characters",
  catFactions: "Factions",
  catLocations: "Locations",
  catGear: "Military Gear",
  addEntry: "New entry",
  entryTitlePh: "Name",
  entrySummaryPh: "One-line summary",
  entryDetailsPh: "Full details, history, notes…",
  deleteEntry: "Delete entry",
  noWikiEntries: "No entries yet. Add your first codex entry.",
  searchWiki: "Search the codex…",
  signInRequired: "Sign in to use this feature.",
  entrySaved: "Saved",
  category: "Category",

  // Auto-hyperlinking
  highlightLore: "Lore links",
  editMode: "Edit text",
  loreLinkHint: "Tap a highlighted name to see its codex card.",
  noMatches: "No codex terms found in this text yet.",
  openInWiki: "Open in codex",
  close: "Close",

  // Notebook tabs / actions
  write: "Write",
  characters: "Characters",
  timeline: "Timeline",
  lore: "Lore",
  startWriting: "Start writing your story…",
  copyText: "Copy text",
  copied: "Story copied to clipboard",
  copyFailed: "Couldn't copy — try again",
  fixGrammar: "Fix grammar",

  // Tutorial
  tutAria: "Getting started tour",
  tutSkip: "Skip tour",
  tutBack: "Back",
  tutNext: "Next",
  tutStart: "Start creating",
  tutWelcomeTitle: "Welcome to Writer Creator",
  tutWelcomeBody: "A single workspace for drafting fiction, designing your cast, mapping your world and sharing chapters with readers. Here's a 30-second tour.",
  tutWriterTitle: "Writer Tools",
  tutWriterBody: "Open Notebooks to write chapters with auto-save, track characters and lore, plan your timeline, set word goals and invite collaborators to a shared notebook chat.",
  tutWikiTitle: "World Wiki & Lore Links",
  tutWikiBody: "Build a codex of characters, factions, locations and gear. While writing, saved names are highlighted automatically — tap one to open its lore card without leaving the editor.",
  tutCanvasTitle: "Drawing Canvas",
  tutCanvasBody: "The Art Studio gives you brushes, a paint bucket, layers, a stroke stabilizer and custom canvas sizes — perfect for character sketches and comic pages.",
  tutMapTitle: "Tactical Map",
  tutMapBody: "In the Tactical Sandbox you can upload a map, sketch terrain, draw vector route arrows, drop glowing markers, add text labels and organise it all with layers.",
} as const;

export type Key = keyof typeof en;

const DICT: Record<LangCode, Partial<Record<Key, string>>> = {
  en: {},
  de: {
    feed: "Globaler Feed", notebooks: "Meine privaten Notizbücher", suggestions: "Vorschlagsbox",
    drawing: "Zeichenstudio", sandbox: "Taktischer Sandkasten", wiki: "Welt-Wiki / Kodex", settings: "Einstellungen",
    jumpToSection: "Zu einem Bereich springen", openMenu: "Menü öffnen", madeBy: "Erstellt von",
    account: "Konto", signOut: "Abmelden", signIn: "Anmelden", signedInAs: "Angemeldet als",
    guest: "Als Gast unterwegs", language: "Sprache", languageHint: "Wähle die Sprache der Benutzeroberfläche.",
    appearance: "Darstellung", darkOnly: "Writer Creators nutzt ein dunkles Studio-Design.",
    wikiSubtitle: "Dein Kodex für Figuren, Fraktionen, Orte und Ausrüstung.",
    allCategories: "Alle", catCharacters: "Figuren", catFactions: "Fraktionen", catLocations: "Orte",
    catGear: "Militärische Ausrüstung", addEntry: "Neuer Eintrag", entryTitlePh: "Name",
    entrySummaryPh: "Kurzbeschreibung in einer Zeile", entryDetailsPh: "Details, Geschichte, Notizen…",
    deleteEntry: "Eintrag löschen", noWikiEntries: "Noch keine Einträge. Füge deinen ersten Kodex-Eintrag hinzu.",
    searchWiki: "Kodex durchsuchen…", signInRequired: "Melde dich an, um diese Funktion zu nutzen.",
    entrySaved: "Gespeichert", category: "Kategorie",
    highlightLore: "Lore-Links", editMode: "Text bearbeiten",
    loreLinkHint: "Tippe auf einen markierten Namen, um die Kodex-Karte zu sehen.",
    noMatches: "In diesem Text wurden noch keine Kodex-Begriffe gefunden.",
    openInWiki: "Im Kodex öffnen", close: "Schließen",
    write: "Schreiben", characters: "Figuren", timeline: "Zeitachse", lore: "Lore",
    startWriting: "Beginne deine Geschichte…", copyText: "Text kopieren",
    copied: "Geschichte in die Zwischenablage kopiert", copyFailed: "Kopieren fehlgeschlagen — versuche es erneut",
    fixGrammar: "Grammatik korrigieren",
    tutAria: "Einführungstour", tutSkip: "Tour überspringen", tutBack: "Zurück", tutNext: "Weiter",
    tutStart: "Los geht's",
    tutWelcomeTitle: "Willkommen bei Writer Creator",
    tutWelcomeBody: "Ein Arbeitsbereich zum Schreiben von Geschichten, Gestalten deiner Figuren, Kartieren deiner Welt und Teilen von Kapiteln. Hier eine 30-Sekunden-Tour.",
    tutWriterTitle: "Schreibwerkzeuge",
    tutWriterBody: "Öffne Notizbücher, um Kapitel mit Auto-Speichern zu schreiben, Figuren und Lore zu verwalten, deine Zeitachse zu planen, Wortziele zu setzen und Mitautoren in den Notizbuch-Chat einzuladen.",
    tutWikiTitle: "Welt-Wiki & Lore-Links",
    tutWikiBody: "Baue einen Kodex aus Figuren, Fraktionen, Orten und Ausrüstung. Beim Schreiben werden gespeicherte Namen automatisch markiert — tippe darauf, um die Lore-Karte zu öffnen, ohne den Editor zu verlassen.",
    tutCanvasTitle: "Zeichenfläche",
    tutCanvasBody: "Das Kunststudio bietet Pinsel, Farbeimer, Ebenen, einen Strich-Stabilisator und eigene Leinwandgrößen — perfekt für Figurenskizzen und Comicseiten.",
    tutMapTitle: "Taktische Karte",
    tutMapBody: "Im Taktischen Sandkasten kannst du Karten hochladen, Gelände skizzieren, Routenpfeile zeichnen, leuchtende Marker setzen, Textlabels hinzufügen und alles in Ebenen organisieren.",
  },
  nl: {
    feed: "Globale feed", notebooks: "Mijn privénotitieboeken", suggestions: "Suggestiebox",
    drawing: "Tekenstudio", sandbox: "Tactische zandbak", wiki: "Wereld-wiki / Codex", settings: "Instellingen",
    jumpToSection: "Ga naar een onderdeel", openMenu: "Menu openen", madeBy: "Gemaakt door",
    account: "Account", signOut: "Afmelden", signIn: "Aanmelden", signedInAs: "Aangemeld als",
    guest: "Je bekijkt als gast", language: "Taal", languageHint: "Kies de taal van de interface.",
    appearance: "Weergave", darkOnly: "Writer Creators gebruikt een donker studiothema.",
    wikiSubtitle: "Jouw codex van personages, facties, locaties en uitrusting.",
    allCategories: "Alles", catCharacters: "Personages", catFactions: "Facties", catLocations: "Locaties",
    catGear: "Militaire uitrusting", addEntry: "Nieuw item", entryTitlePh: "Naam",
    entrySummaryPh: "Samenvatting in één regel", entryDetailsPh: "Details, geschiedenis, notities…",
    deleteEntry: "Item verwijderen", noWikiEntries: "Nog geen items. Voeg je eerste codex-item toe.",
    searchWiki: "Zoek in de codex…", signInRequired: "Meld je aan om deze functie te gebruiken.",
    entrySaved: "Opgeslagen", category: "Categorie",
    highlightLore: "Lore-links", editMode: "Tekst bewerken",
    loreLinkHint: "Tik op een gemarkeerde naam om de codexkaart te zien.",
    noMatches: "Nog geen codextermen gevonden in deze tekst.",
    openInWiki: "Openen in codex", close: "Sluiten",
    write: "Schrijven", characters: "Personages", timeline: "Tijdlijn", lore: "Lore",
    startWriting: "Begin je verhaal…", copyText: "Tekst kopiëren",
    copied: "Verhaal gekopieerd naar klembord", copyFailed: "Kopiëren mislukt — probeer opnieuw",
    fixGrammar: "Grammatica verbeteren",
    tutAria: "Introductietour", tutSkip: "Tour overslaan", tutBack: "Terug", tutNext: "Volgende",
    tutStart: "Begin met creëren",
    tutWelcomeTitle: "Welkom bij Writer Creator",
    tutWelcomeBody: "Één werkruimte om fictie te schrijven, je personages te ontwerpen, je wereld te tekenen en hoofdstukken te delen met lezers. Hier is een tour van 30 seconden.",
    tutWriterTitle: "Schrijfgereedschap",
    tutWriterBody: "Open Notitieboeken om hoofdstukken te schrijven met automatisch opslaan, personages en lore bij te houden, je tijdlijn te plannen, woorddoelen te stellen en medeauteurs uit te nodigen in de notitieboekchat.",
    tutWikiTitle: "Wereld-wiki & lore-links",
    tutWikiBody: "Bouw een codex van personages, facties, locaties en uitrusting. Tijdens het schrijven worden opgeslagen namen automatisch gemarkeerd — tik erop om de lorekaart te openen zonder de editor te verlaten.",
    tutCanvasTitle: "Tekencanvas",
    tutCanvasBody: "De kunststudio biedt penselen, een vulemmer, lagen, een lijnstabilisator en eigen canvasformaten — perfect voor personageschetsen en strippagina's.",
    tutMapTitle: "Tactische kaart",
    tutMapBody: "In de tactische zandbak kun je een kaart uploaden, terrein schetsen, routepijlen tekenen, gloeiende markers plaatsen, tekstlabels toevoegen en alles met lagen organiseren.",
  },
  fr: {
    feed: "Fil global", notebooks: "Mes carnets privés", suggestions: "Boîte à suggestions",
    drawing: "Studio de dessin", sandbox: "Bac à sable tactique", wiki: "Wiki du monde / Codex", settings: "Paramètres",
    jumpToSection: "Aller à une section", openMenu: "Ouvrir le menu", madeBy: "Créé par",
    account: "Compte", signOut: "Se déconnecter", signIn: "Se connecter", signedInAs: "Connecté en tant que",
    guest: "Navigation en invité", language: "Langue", languageHint: "Choisissez la langue de l'interface.",
    appearance: "Apparence", darkOnly: "Writer Creators utilise un thème studio sombre.",
    wikiSubtitle: "Votre codex de personnages, factions, lieux et équipements.",
    allCategories: "Tout", catCharacters: "Personnages", catFactions: "Factions", catLocations: "Lieux",
    catGear: "Équipement militaire", addEntry: "Nouvelle fiche", entryTitlePh: "Nom",
    entrySummaryPh: "Résumé en une ligne", entryDetailsPh: "Détails, histoire, notes…",
    deleteEntry: "Supprimer la fiche", noWikiEntries: "Aucune fiche pour l'instant. Ajoutez votre première fiche.",
    searchWiki: "Rechercher dans le codex…", signInRequired: "Connectez-vous pour utiliser cette fonction.",
    entrySaved: "Enregistré", category: "Catégorie",
    highlightLore: "Liens du codex", editMode: "Modifier le texte",
    loreLinkHint: "Touchez un nom surligné pour voir sa fiche.",
    noMatches: "Aucun terme du codex trouvé dans ce texte.",
    openInWiki: "Ouvrir dans le codex", close: "Fermer",
    write: "Écrire", characters: "Personnages", timeline: "Chronologie", lore: "Univers",
    startWriting: "Commencez votre histoire…", copyText: "Copier le texte",
    copied: "Histoire copiée dans le presse-papiers", copyFailed: "Copie impossible — réessayez",
    fixGrammar: "Corriger la grammaire",
    tutAria: "Visite de démarrage", tutSkip: "Passer la visite", tutBack: "Retour", tutNext: "Suivant",
    tutStart: "Commencer à créer",
    tutWelcomeTitle: "Bienvenue sur Writer Creator",
    tutWelcomeBody: "Un espace unique pour écrire vos fictions, concevoir vos personnages, cartographier votre monde et partager vos chapitres. Voici une visite de 30 secondes.",
    tutWriterTitle: "Outils d'écriture",
    tutWriterBody: "Ouvrez les carnets pour écrire des chapitres avec sauvegarde automatique, suivre personnages et univers, planifier votre chronologie, fixer des objectifs de mots et inviter des collaborateurs au chat du carnet.",
    tutWikiTitle: "Wiki du monde et liens du codex",
    tutWikiBody: "Créez un codex de personnages, factions, lieux et équipements. Pendant l'écriture, les noms enregistrés sont surlignés automatiquement — touchez-en un pour ouvrir sa fiche sans quitter l'éditeur.",
    tutCanvasTitle: "Toile de dessin",
    tutCanvasBody: "Le studio d'art offre des pinceaux, un pot de peinture, des calques, un stabilisateur de tracé et des tailles de toile personnalisées — parfait pour les croquis et les planches de BD.",
    tutMapTitle: "Carte tactique",
    tutMapBody: "Dans le bac à sable tactique, importez une carte, esquissez le terrain, tracez des flèches d'itinéraire, posez des marqueurs lumineux, ajoutez des étiquettes et organisez le tout en calques.",
  },
  es: {
    feed: "Feed global", notebooks: "Mis cuadernos privados", suggestions: "Buzón de sugerencias",
    drawing: "Estudio de dibujo", sandbox: "Arenero táctico", wiki: "Wiki del mundo / Códice", settings: "Ajustes",
    jumpToSection: "Ir a una sección", openMenu: "Abrir menú", madeBy: "Hecho por",
    account: "Cuenta", signOut: "Cerrar sesión", signIn: "Iniciar sesión", signedInAs: "Sesión iniciada como",
    guest: "Navegando como invitado", language: "Idioma", languageHint: "Elige el idioma de la interfaz.",
    appearance: "Apariencia", darkOnly: "Writer Creators usa un tema de estudio oscuro.",
    wikiSubtitle: "Tu códice de personajes, facciones, lugares y equipo.",
    allCategories: "Todo", catCharacters: "Personajes", catFactions: "Facciones", catLocations: "Lugares",
    catGear: "Equipo militar", addEntry: "Nueva entrada", entryTitlePh: "Nombre",
    entrySummaryPh: "Resumen en una línea", entryDetailsPh: "Detalles, historia, notas…",
    deleteEntry: "Eliminar entrada", noWikiEntries: "Aún no hay entradas. Añade tu primera entrada del códice.",
    searchWiki: "Buscar en el códice…", signInRequired: "Inicia sesión para usar esta función.",
    entrySaved: "Guardado", category: "Categoría",
    highlightLore: "Enlaces del códice", editMode: "Editar texto",
    loreLinkHint: "Toca un nombre resaltado para ver su ficha.",
    noMatches: "Aún no se encontraron términos del códice en este texto.",
    openInWiki: "Abrir en el códice", close: "Cerrar",
    write: "Escribir", characters: "Personajes", timeline: "Cronología", lore: "Trasfondo",
    startWriting: "Empieza tu historia…", copyText: "Copiar texto",
    copied: "Historia copiada al portapapeles", copyFailed: "No se pudo copiar — inténtalo de nuevo",
    fixGrammar: "Corregir gramática",
    tutAria: "Tour de inicio", tutSkip: "Omitir tour", tutBack: "Atrás", tutNext: "Siguiente",
    tutStart: "Empezar a crear",
    tutWelcomeTitle: "Bienvenido a Writer Creator",
    tutWelcomeBody: "Un único espacio para escribir ficción, diseñar tu reparto, cartografiar tu mundo y compartir capítulos con lectores. Aquí tienes un tour de 30 segundos.",
    tutWriterTitle: "Herramientas de escritura",
    tutWriterBody: "Abre los cuadernos para escribir capítulos con autoguardado, gestionar personajes y trasfondo, planificar tu cronología, fijar metas de palabras e invitar colaboradores al chat del cuaderno.",
    tutWikiTitle: "Wiki del mundo y enlaces de trasfondo",
    tutWikiBody: "Crea un códice de personajes, facciones, lugares y equipo. Al escribir, los nombres guardados se resaltan automáticamente: tócalos para abrir su ficha sin salir del editor.",
    tutCanvasTitle: "Lienzo de dibujo",
    tutCanvasBody: "El estudio de arte ofrece pinceles, cubo de pintura, capas, estabilizador de trazo y tamaños de lienzo personalizados — ideal para bocetos y páginas de cómic.",
    tutMapTitle: "Mapa táctico",
    tutMapBody: "En el arenero táctico puedes subir un mapa, dibujar terreno, trazar flechas de ruta, colocar marcadores brillantes, añadir etiquetas y organizarlo todo con capas.",
  },
  pt: {
    feed: "Feed global", notebooks: "Meus cadernos privados", suggestions: "Caixa de sugestões",
    drawing: "Estúdio de desenho", sandbox: "Caixa de areia tática", wiki: "Wiki do mundo / Códice", settings: "Configurações",
    jumpToSection: "Ir para uma seção", openMenu: "Abrir menu", madeBy: "Feito por",
    account: "Conta", signOut: "Sair", signIn: "Entrar", signedInAs: "Conectado como",
    guest: "Navegando como visitante", language: "Idioma", languageHint: "Escolha o idioma da interface.",
    appearance: "Aparência", darkOnly: "Writer Creators usa um tema de estúdio escuro.",
    wikiSubtitle: "Seu códice de personagens, facções, locais e equipamentos.",
    allCategories: "Tudo", catCharacters: "Personagens", catFactions: "Facções", catLocations: "Locais",
    catGear: "Equipamento militar", addEntry: "Nova entrada", entryTitlePh: "Nome",
    entrySummaryPh: "Resumo em uma linha", entryDetailsPh: "Detalhes, história, notas…",
    deleteEntry: "Excluir entrada", noWikiEntries: "Nenhuma entrada ainda. Adicione a primeira do seu códice.",
    searchWiki: "Pesquisar no códice…", signInRequired: "Entre para usar este recurso.",
    entrySaved: "Salvo", category: "Categoria",
    highlightLore: "Links do códice", editMode: "Editar texto",
    loreLinkHint: "Toque num nome destacado para ver a ficha dele.",
    noMatches: "Nenhum termo do códice encontrado neste texto ainda.",
    openInWiki: "Abrir no códice", close: "Fechar",
    write: "Escrever", characters: "Personagens", timeline: "Linha do tempo", lore: "Universo",
    startWriting: "Comece a sua história…", copyText: "Copiar texto",
    copied: "História copiada para a área de transferência", copyFailed: "Não foi possível copiar — tente novamente",
    fixGrammar: "Corrigir gramática",
    tutAria: "Tour inicial", tutSkip: "Pular tour", tutBack: "Voltar", tutNext: "Próximo",
    tutStart: "Começar a criar",
    tutWelcomeTitle: "Bem-vindo ao Writer Creator",
    tutWelcomeBody: "Um espaço único para escrever ficção, criar seu elenco, mapear seu mundo e compartilhar capítulos com leitores. Veja um tour de 30 segundos.",
    tutWriterTitle: "Ferramentas de escrita",
    tutWriterBody: "Abra os cadernos para escrever capítulos com salvamento automático, acompanhar personagens e universo, planejar sua linha do tempo, definir metas de palavras e convidar colaboradores para o chat do caderno.",
    tutWikiTitle: "Wiki do mundo e links de universo",
    tutWikiBody: "Monte um códice de personagens, facções, locais e equipamentos. Ao escrever, os nomes salvos são destacados automaticamente — toque num deles para abrir a ficha sem sair do editor.",
    tutCanvasTitle: "Tela de desenho",
    tutCanvasBody: "O estúdio de arte oferece pincéis, balde de tinta, camadas, estabilizador de traço e tamanhos de tela personalizados — perfeito para esboços e páginas de quadrinhos.",
    tutMapTitle: "Mapa tático",
    tutMapBody: "Na caixa de areia tática você pode enviar um mapa, esboçar terreno, desenhar setas de rota, colocar marcadores brilhantes, adicionar rótulos e organizar tudo em camadas.",
  },
  ar: {
    feed: "الموجز العام", notebooks: "دفاتري الخاصة", suggestions: "صندوق الاقتراحات",
    drawing: "استوديو الرسم", sandbox: "الساحة التكتيكية", wiki: "موسوعة العالم / الكودكس", settings: "الإعدادات",
    jumpToSection: "الانتقال إلى قسم", openMenu: "فتح القائمة", madeBy: "من إعداد",
    account: "الحساب", signOut: "تسجيل الخروج", signIn: "تسجيل الدخول", signedInAs: "مسجّل الدخول باسم",
    guest: "تتصفح كزائر", language: "اللغة", languageHint: "اختر لغة واجهة التطبيق.",
    appearance: "المظهر", darkOnly: "يستخدم Writer Creators مظهرًا داكنًا.",
    wikiSubtitle: "موسوعتك للشخصيات والفصائل والأماكن والعتاد.",
    allCategories: "الكل", catCharacters: "الشخصيات", catFactions: "الفصائل", catLocations: "الأماكن",
    catGear: "العتاد العسكري", addEntry: "مدخل جديد", entryTitlePh: "الاسم",
    entrySummaryPh: "ملخص في سطر واحد", entryDetailsPh: "التفاصيل والتاريخ والملاحظات…",
    deleteEntry: "حذف المدخل", noWikiEntries: "لا مداخل بعد. أضف أول مدخل في موسوعتك.",
    searchWiki: "ابحث في الموسوعة…", signInRequired: "سجّل الدخول لاستخدام هذه الميزة.",
    entrySaved: "تم الحفظ", category: "الفئة",
    highlightLore: "روابط الموسوعة", editMode: "تحرير النص",
    loreLinkHint: "اضغط على اسم مُبرز لعرض بطاقته.",
    noMatches: "لم يتم العثور على مصطلحات من الموسوعة في هذا النص بعد.",
    openInWiki: "فتح في الموسوعة", close: "إغلاق",
    write: "الكتابة", characters: "الشخصيات", timeline: "الخط الزمني", lore: "خلفية العالم",
    startWriting: "ابدأ كتابة قصتك…", copyText: "نسخ النص",
    copied: "تم نسخ القصة إلى الحافظة", copyFailed: "تعذّر النسخ — حاول مرة أخرى",
    fixGrammar: "تصحيح القواعد",
    tutAria: "جولة البداية", tutSkip: "تخطي الجولة", tutBack: "رجوع", tutNext: "التالي",
    tutStart: "ابدأ الإبداع",
    tutWelcomeTitle: "مرحبًا بك في Writer Creator",
    tutWelcomeBody: "مساحة واحدة لكتابة القصص وتصميم شخصياتك ورسم خريطة عالمك ومشاركة الفصول مع القراء. إليك جولة من 30 ثانية.",
    tutWriterTitle: "أدوات الكتابة",
    tutWriterBody: "افتح الدفاتر لكتابة الفصول مع الحفظ التلقائي، وتتبع الشخصيات وخلفية العالم، وتخطيط الخط الزمني، وتحديد أهداف الكلمات، ودعوة المتعاونين إلى دردشة الدفتر.",
    tutWikiTitle: "موسوعة العالم وروابط الخلفية",
    tutWikiBody: "ابنِ موسوعة للشخصيات والفصائل والأماكن والعتاد. أثناء الكتابة تُبرز الأسماء المحفوظة تلقائيًا — اضغط على أحدها لعرض بطاقتها دون مغادرة المحرر.",
    tutCanvasTitle: "لوحة الرسم",
    tutCanvasBody: "يمنحك استوديو الفن فرشًا ودلو تلوين وطبقات ومثبّت خطوط وأحجام لوحات مخصصة — مثالي لرسم الشخصيات وصفحات القصص المصورة.",
    tutMapTitle: "الخريطة التكتيكية",
    tutMapBody: "في الساحة التكتيكية يمكنك تحميل خريطة ورسم التضاريس ورسم أسهم المسارات ووضع علامات متوهجة وإضافة نصوص وتنظيم كل شيء بالطبقات.",
  },
  zh: {
    feed: "全球动态", notebooks: "我的私人笔记本", suggestions: "建议箱",
    drawing: "绘画工作室", sandbox: "战术沙盘", wiki: "世界百科 / 图鉴", settings: "设置",
    jumpToSection: "跳转到板块", openMenu: "打开菜单", madeBy: "制作者",
    account: "账户", signOut: "退出登录", signIn: "登录", signedInAs: "已登录：",
    guest: "以访客身份浏览", language: "语言", languageHint: "选择应用界面语言。",
    appearance: "外观", darkOnly: "Writer Creators 使用深色工作室主题。",
    wikiSubtitle: "你的角色、势力、地点与装备图鉴。",
    allCategories: "全部", catCharacters: "角色", catFactions: "势力", catLocations: "地点",
    catGear: "军事装备", addEntry: "新建条目", entryTitlePh: "名称",
    entrySummaryPh: "一句话简介", entryDetailsPh: "详细内容、历史、备注…",
    deleteEntry: "删除条目", noWikiEntries: "还没有条目。添加第一个图鉴条目。",
    searchWiki: "搜索图鉴…", signInRequired: "登录后即可使用此功能。",
    entrySaved: "已保存", category: "分类",
    highlightLore: "设定链接", editMode: "编辑文本",
    loreLinkHint: "点击高亮的名称即可查看图鉴卡片。",
    noMatches: "此文本中尚未发现图鉴词条。",
    openInWiki: "在图鉴中打开", close: "关闭",
    write: "写作", characters: "角色", timeline: "时间线", lore: "设定",
    startWriting: "开始写你的故事…", copyText: "复制文本",
    copied: "故事已复制到剪贴板", copyFailed: "复制失败——请重试",
    fixGrammar: "修正语法",
    tutAria: "新手导览", tutSkip: "跳过导览", tutBack: "上一步", tutNext: "下一步",
    tutStart: "开始创作",
    tutWelcomeTitle: "欢迎使用 Writer Creator",
    tutWelcomeBody: "一个集写作、角色设计、世界地图与章节分享于一体的工作空间。这是一段 30 秒的导览。",
    tutWriterTitle: "写作工具",
    tutWriterBody: "打开笔记本即可自动保存地撰写章节、管理角色与设定、规划时间线、设定字数目标，并邀请协作者加入笔记本聊天。",
    tutWikiTitle: "世界百科与设定链接",
    tutWikiBody: "建立角色、势力、地点与装备的图鉴。写作时已保存的名称会自动高亮——点击即可在不离开编辑器的情况下查看设定卡片。",
    tutCanvasTitle: "绘画画布",
    tutCanvasBody: "艺术工作室提供画笔、油漆桶、图层、笔迹稳定器和自定义画布尺寸——非常适合角色草图与漫画页面。",
    tutMapTitle: "战术地图",
    tutMapBody: "在战术沙盘中，你可以上传地图、勾画地形、绘制路线箭头、放置发光标记、添加文字标签，并用图层进行整理。",
  },
};

type Ctx = { lang: LangCode; setLang: (l: LangCode) => void; t: (k: Key) => string };
const LanguageContext = createContext<Ctx | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>("en");

  useEffect(() => {
    try {
      const saved = window.localStorage.getItem("dd:lang") as LangCode | null;
      if (saved && LANGUAGES.some((l) => l.code === saved)) setLangState(saved);
    } catch {}
  }, []);

  useEffect(() => {
    if (typeof document === "undefined") return;
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, [lang]);

  const setLang = (l: LangCode) => {
    setLangState(l);
    try { window.localStorage.setItem("dd:lang", l); } catch {}
  };

  const t = (k: Key) => DICT[lang]?.[k] ?? en[k];

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) return { lang: "en" as LangCode, setLang: () => {}, t: (k: Key) => en[k] };
  return ctx;
}
